language: node_js
node_js:
  - 6

env:
  - NODE_ENV=travis

services:
  - mongodb
  - postgresql
  - redis-server

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - psql -c 'create database burgerstack_test;' -U postgres
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

sudo: false

os:
  - linux

branches:
  only: master

script:
  - npm run travis

after_success:
  - bash <(curl -s https://codecov.io/bash)
