language: node_js
node_js:
  - 6

env:
  - NODE_ENV=travis

services:
  - mongodb
  - postgresql
  - redis-server

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - psql -c 'create database burgerstack_test;' -U postgres

sudo: false

os:
  - linux

branches:
  only: master

script:
  - npm test
